##
# Local postgres Database Configuration
##
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nc_phone_company_local?user=yzrllkhondutsx&password=postgres
    driver-class-name: org.postgresql.Driver