##
# Local postgres Database Configuration
##
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nc_phone_company_local?user=yzrllkhondutsx&password=root
    driver-class-name: org.postgresql.Driver
    tomcat:
          max-active: 8