##
# Embedded H2 Database Configuration
##
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:D:/myDB
    data: data.sql
    schema: schema.sql
    password: root
    username: root