server:
  port: 8090

spring:
  profiles:
    active: dev
  thymeleaf:
    cache: false

logging:
  level:
    com:
      phonecompany: debug

security:
  basic:
   enabled: false

application-url: http://localhost:8090/api