server:
  port: 8090

spring:
  profiles:
    active: prod

logging:
  level:
    com:
      phonecompany: debug

security:
  basic:
   enabled: false

application-url: https://phone-company.herokuapp.com/api
registration-success-url: https://phone-company.herokuapp.com/#/login/success