##
# Heroku Postgresql Configuration
##
spring:
  datasource:
    url: jdbc:postgresql://ec2-54-228-182-57.eu-west-1.compute.amazonaws.com:5432/d7lnt6ggk9rcbt?user=tkacgwphjmxbcr&password=7b30fa8db77649da5b55ee2cd64b3c4399ef8feebc020417391b05121563b024&ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
    driver-class-name: org.postgresql.Driver