server:
  port: 8090

spring:
  profiles:
    active: prod
  thymeleaf:
    cache: false

logging:
  level:
    com:
      phonecompany: info

security:
  basic:
   enabled: false

application-url: https://phone-company.herokuapp.com/api