##
# Embedded H2 Database Configuration
##
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/myDB;MV_STORE=false
    username: root
    password: root
    data: data.sql
    schema: schema.sql