server:
  port: 8090

spring:
  profiles:
    active: prod
  thymeleaf:
    prefix: classpath:/templates

logging:
  level:
    com:
      phonecompany: info

security:
  basic:
   enabled: false

application-url: http://localhost:8090/api