active: localds
profiles:
  - name: prod
    datasource:
      url: jdbc:postgresql://ec2-23-23-244-83.compute-1.amazonaws.com:5432/d9860gpavsh57b?user=yzrllkhondutsx&password=99ecc04560666945bc95824b30d33b575478c323076284b6e4ea39362633dd4d&ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
      driver-class-name: org.postgresql.Driver
      username: yzrllkhondutsx
      password: 99ecc04560666945bc95824b30d33b575478c323076284b6e4ea39362633dd4d
  - name: dev
    datasource:
      url: jdbc:postgresql://localhost:5432/phone-company?user=postgres&password=1111
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: 1111
  - name: localds
    datasource:
      url: jdbc:postgresql://localhost:5432/nc_phone_company_local?user=yzrllkhondutsx&password=root
      driver-class-name: org.postgresql.Driver
      username: yzrllkhondutsx
      password: root