server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://ec2-23-23-244-83.compute-1.amazonaws.com:5432/d9860gpavsh57b?user=yzrllkhondutsx&password=99ecc04560666945bc95824b30d33b575478c323076284b6e4ea39362633dd4d&ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
    initialize: false
    tomcat:
          max-active: 2
          max-idle: 2
logging:
  level:
    com:
      phonecompany: debug